parameters:
  - name: cfg
    type: string
    default: "Release"

  - name: folder
    type: string
    default: ""

  - name: artifact
    type: string
    default: "drop"

steps:
  - task: UseDotNet@2
    displayName: "Install .NET 6 SDK"
    inputs:
      packageType: "sdk"
      version: "6.x"

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "${{ parameters.folder }}/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build the project - ${{ parameters.cfg }}"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration ${{ parameters.cfg }}"
      projects: "${{ parameters.folder }}/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Publish the project - ${{ parameters.cfg }}"
    inputs:
      command: "publish"
      projects: "${{ parameters.folder }}/*.csproj"
      publishWebProjects: false
      arguments: "--no-build --configuration ${{ parameters.cfg }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.cfg }}"
      zipAfterPublish: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetapp: $(ArtifactStagingDirectory)
      artifact: ${{ parameters.artifact }}
      publishLocation: 'pipeline'
