name: api mend

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: "Release"
  app: apps/config-api/

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
    inputs:
      version: "$(dotnetSdkVersion)"

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "$(app)/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build the project - $(buildConfiguration)"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration $(buildConfiguration)"
      projects: "$(app)/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Publish the project - $(buildConfiguration)"
    inputs:
      command: "publish"
      projects: "$(app)/*.csproj"
      publishWebProjects: false
      arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
      zipAfterPublish: true

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
      projectName: 'Config-Api'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    condition: succeeded()
